### ISSUE TITLE
Improve russian translation

### ISSUE THREAD

**Issue by maxsimych** [dvopalecky/gen-mapper#4]
Hello, thank you for the instrument!
I see that the project is not completely translated to russian, I can help you with that!

**Comment by dvopalecky** [comment]
Hello Maxim, thanks, feel free to make a pull request with the improved translation, and I will add it.
Also, note that I'm no longer improving this project. Please see another project at https://noplaceleft.tools, where the genmapper is being improved by another developer. You can possibly contact them at support@noplaceleft.tools.

**Comment by maxsimych** [comment]
Ok, thanks, then I will contact them.
